"use client";

import { useState, useEffect, useRef, useCallback, useMemo } from "react";
import Image from "next/image";
import {
  Send,
  Loader2,
  Mic,
  MicOff,
  FileCode,
  Globe,
  Cpu,
  DollarSign,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from "react-markdown";
import {
  ReactFlow,
  Background,
  Controls,
  Handle,
  Position,
  ReactFlowProvider,
  useNodesState,
  useEdgesState,
  type Node,
  type Edge,
  type NodeProps,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { Badge } from "@/components/ui/badge";
import {
  calculateMVPQuote,
  defaultConfiguratorData,
  type FlowData,
  type FlowNodeData,
} from "@/config/mvp-pricing";
import { saveSession } from "./actions";

// ---------- Types ----------

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface BlockData {
  type: "page" | "externalApi" | "customLogic";
  name: string;
  description: string;
}

interface EdgeData {
  sourceName: string;
  targetName: string;
}

interface SessionData {
  id: string;
  email: string;
  name: string | null;
  flowData: unknown;
  chatHistory: unknown;
  quoteTotal: number | null;
}

interface MvpPlannerClientProps {
  session: SessionData;
  userName: string;
}

// ---------- Diagram Node Components ----------

function PlannerPageNode({ data }: NodeProps) {
  const d = data as FlowNodeData["data"];
  return (
    <div
      className={`min-w-[160px] rounded-lg border-2 ${
        d.isIncluded
          ? "border-primary-500 bg-primary-50"
          : d.isAutoGenerated
            ? "border-primary-300 bg-primary-50/50"
            : "border-primary-400 bg-white"
      } p-3 shadow-sm`}
    >
      <Handle
        type="target"
        position={Position.Left}
        className="!size-3 !bg-primary-500"
      />
      <div className="flex items-start gap-2">
        <FileCode className="mt-0.5 size-4 shrink-0 text-primary-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {d.name}
          </p>
          {d.description && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {d.description}
            </p>
          )}
          {d.isIncluded && (
            <Badge variant="secondary" className="mt-1 text-[10px]">
              Included
            </Badge>
          )}
        </div>
      </div>
      <Handle
        type="source"
        position={Position.Right}
        className="!size-3 !bg-primary-500"
      />
    </div>
  );
}

function PlannerApiNode({ data }: NodeProps) {
  const d = data as FlowNodeData["data"];
  return (
    <div className="min-w-[160px] rounded-lg border-2 border-success-400 bg-white p-3 shadow-sm">
      <Handle
        type="target"
        position={Position.Left}
        className="!size-3 !bg-success-500"
      />
      <div className="flex items-start gap-2">
        <Globe className="mt-0.5 size-4 shrink-0 text-success-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {d.name}
          </p>
          {d.description && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {d.description}
            </p>
          )}
        </div>
      </div>
      <Handle
        type="source"
        position={Position.Right}
        className="!size-3 !bg-success-500"
      />
    </div>
  );
}

function PlannerCustomLogicNode({ data }: NodeProps) {
  const d = data as FlowNodeData["data"];
  return (
    <div className="min-w-[160px] rounded-lg border-2 border-warning-400 bg-white p-3 shadow-sm">
      <Handle
        type="target"
        position={Position.Left}
        className="!size-3 !bg-warning-500"
      />
      <div className="flex items-start gap-2">
        <Cpu className="mt-0.5 size-4 shrink-0 text-warning-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {d.name}
          </p>
          {d.description && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {d.description}
            </p>
          )}
        </div>
      </div>
      <Handle
        type="source"
        position={Position.Right}
        className="!size-3 !bg-warning-500"
      />
    </div>
  );
}

const nodeTypes = {
  page: PlannerPageNode,
  externalApi: PlannerApiNode,
  customLogic: PlannerCustomLogicNode,
};

// ---------- Layout Helpers ----------

const COLUMN_CONFIG: Record<string, { x: number; label: string }> = {
  page: { x: 50, label: "Pages" },
  externalApi: { x: 350, label: "Integrations" },
  customLogic: { x: 650, label: "Logic" },
};

const Y_START = 30;
const Y_GAP = 120;

function autoLayoutNodes(nodes: Node[]): Node[] {
  const counters: Record<string, number> = { page: 0, externalApi: 0, customLogic: 0 };

  return nodes.map((node) => {
    const col = COLUMN_CONFIG[node.type || "page"] || COLUMN_CONFIG.page;
    const index = counters[node.type || "page"] || 0;
    counters[node.type || "page"] = index + 1;

    return {
      ...node,
      position: { x: col.x, y: Y_START + index * Y_GAP },
    };
  });
}

// ---------- Main Component ----------

function MvpPlannerInner({ session, userName }: MvpPlannerClientProps) {
  // Restore chat history from session or start fresh
  const initialMessages: ChatMessage[] = useMemo(() => {
    if (
      session.chatHistory &&
      Array.isArray(session.chatHistory) &&
      session.chatHistory.length > 0
    ) {
      return session.chatHistory as ChatMessage[];
    }
    return [];
  }, [session.chatHistory]);

  // Restore flow data from session
  const initialNodes: Node[] = useMemo(() => {
    if (session.flowData) {
      const fd = session.flowData as FlowData;
      if (fd.nodes && fd.nodes.length > 0) {
        return fd.nodes.map((n) => ({
          id: n.id,
          type: n.type,
          position: n.position,
          data: n.data,
        }));
      }
    }
    return [];
  }, [session.flowData]);

  const initialEdges: Edge[] = useMemo(() => {
    if (session.flowData) {
      const fd = session.flowData as FlowData;
      if (fd.edges && fd.edges.length > 0) {
        return fd.edges.map((e) => ({
          id: e.id,
          source: e.source,
          target: e.target,
        }));
      }
    }
    return [];
  }, [session.flowData]);

  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [inputValue, setInputValue] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

  // Voice input state
  const [isListening, setIsListening] = useState(false);
  const [voiceSupported, setVoiceSupported] = useState(false);
  const recognitionRef = useRef<SpeechRecognition | null>(null);

  const chatContainerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const hasTriggeredInitial = useRef(false);

  // Check voice support
  useEffect(() => {
    const SpeechRecognition =
      window.SpeechRecognition || window.webkitSpeechRecognition;
    setVoiceSupported(!!SpeechRecognition);
  }, []);

  // Quote calculation
  const quoteTotal = useMemo(() => {
    const flowData: FlowData = {
      nodes: nodes.map((n) => ({
        id: n.id,
        type: n.type as FlowNodeData["type"],
        position: n.position,
        data: n.data as FlowNodeData["data"],
      })),
      edges: edges.map((e) => ({
        id: e.id,
        source: e.source,
        target: e.target,
      })),
    };
    return calculateMVPQuote(flowData, defaultConfiguratorData);
  }, [nodes, edges]);

  // Auto-scroll chat
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop =
        chatContainerRef.current.scrollHeight;
    }
  }, [messages, isLoading]);

  // Auto-save (debounced)
  const triggerSave = useCallback(() => {
    if (saveTimeoutRef.current) clearTimeout(saveTimeoutRef.current);
    saveTimeoutRef.current = setTimeout(() => {
      const flowData: FlowData = {
        nodes: nodes.map((n) => ({
          id: n.id,
          type: n.type as FlowNodeData["type"],
          position: n.position,
          data: n.data as FlowNodeData["data"],
        })),
        edges: edges.map((e) => ({
          id: e.id,
          source: e.source,
          target: e.target,
        })),
      };
      saveSession(session.id, flowData, messages, quoteTotal.total);
    }, 2000);
  }, [nodes, edges, messages, quoteTotal.total, session.id]);

  useEffect(() => {
    if (messages.length > 0 || nodes.length > 0) {
      triggerSave();
    }
  }, [messages, nodes, edges, triggerSave]);

  // Trigger initial AI message if no chat history
  useEffect(() => {
    if (hasTriggeredInitial.current) return;
    if (initialMessages.length > 0) return;
    hasTriggeredInitial.current = true;

    const greet = async () => {
      setIsLoading(true);
      try {
        const greeting = userName
          ? `Hi, my name is ${userName}. I just booked a call.`
          : "Hi, I just booked a call.";

        const response = await fetch("/api/chat/mvp-planner", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            messages: [{ role: "user", content: greeting }],
            currentNodes: [],
          }),
        });

        if (!response.ok) throw new Error("Failed");

        const data = await response.json();
        setMessages([
          { role: "user", content: greeting },
          { role: "assistant", content: data.message },
        ]);

        if (data.blocks && data.blocks.length > 0) {
          addBlocksToGraph(data.blocks, data.edges || []);
        }
      } catch {
        setMessages([
          {
            role: "assistant",
            content:
              "Welcome! I'll help you plan your MVP and give you a rough quote. Tell me about what you're building - what problem does your product solve?",
          },
        ]);
      } finally {
        setIsLoading(false);
      }
    };

    greet();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Add blocks and edges to the graph
  const addBlocksToGraph = useCallback(
    (blocks: BlockData[], newEdges: EdgeData[]) => {
      setNodes((prev) => {
        const existingNames = new Set(
          prev.map((n) => (n.data as FlowNodeData["data"]).name?.toLowerCase())
        );
        const newNodes: Node[] = [];

        for (const block of blocks) {
          if (existingNames.has(block.name.toLowerCase())) continue;
          existingNames.add(block.name.toLowerCase());

          newNodes.push({
            id: `planner-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
            type: block.type,
            position: { x: 0, y: 0 },
            data: {
              name: block.name,
              description: block.description,
              isIncluded:
                block.name.toLowerCase() === "dashboard" ||
                block.name.toLowerCase().includes("settings"),
            },
          });
        }

        if (newNodes.length === 0) return prev;

        const combined = [...prev, ...newNodes];
        return autoLayoutNodes(combined);
      });

      if (newEdges && newEdges.length > 0) {
        setEdges((prev) => {
          const allNodes = [...nodes];
          const addedEdges: Edge[] = [];

          for (const e of newEdges) {
            const sourceNode = allNodes.find(
              (n) =>
                (n.data as FlowNodeData["data"]).name?.toLowerCase() ===
                e.sourceName.toLowerCase()
            );
            const targetNode = allNodes.find(
              (n) =>
                (n.data as FlowNodeData["data"]).name?.toLowerCase() ===
                e.targetName.toLowerCase()
            );

            if (sourceNode && targetNode) {
              addedEdges.push({
                id: `edge-${sourceNode.id}-${targetNode.id}`,
                source: sourceNode.id,
                target: targetNode.id,
              });
            }
          }

          return [...prev, ...addedEdges];
        });
      }
    },
    [nodes, setNodes, setEdges]
  );

  // Send message
  const handleSend = useCallback(async () => {
    const text = inputValue.trim();
    if (!text || isLoading) return;

    const newMessages: ChatMessage[] = [
      ...messages,
      { role: "user", content: text },
    ];
    setMessages(newMessages);
    setInputValue("");
    setIsLoading(true);

    // Stop listening if voice is active
    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
    }

    try {
      const currentNodesSummary = nodes.map((n) => ({
        id: n.id,
        type: n.type as string,
        name: (n.data as FlowNodeData["data"]).name,
        description: (n.data as FlowNodeData["data"]).description,
      }));

      const response = await fetch("/api/chat/mvp-planner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: newMessages,
          currentNodes: currentNodesSummary,
        }),
      });

      if (!response.ok) throw new Error("Failed to send message");

      const data = await response.json();

      setMessages((prev) => [
        ...prev,
        { role: "assistant", content: data.message },
      ]);

      if (data.blocks && data.blocks.length > 0) {
        addBlocksToGraph(data.blocks, data.edges || []);
      }
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "Sorry, something went wrong. Please try again.",
        },
      ]);
    } finally {
      setIsLoading(false);
    }
  }, [inputValue, isLoading, messages, nodes, isListening, addBlocksToGraph]);

  // Voice toggle
  const toggleVoice = useCallback(() => {
    if (!voiceSupported) return;

    if (isListening) {
      recognitionRef.current?.stop();
      setIsListening(false);
      return;
    }

    const SpeechRecognitionCtor =
      window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognitionCtor) return;
    const recognition = new SpeechRecognitionCtor();
    recognition.continuous = true;
    recognition.interimResults = true;
    recognition.lang = "en-US";

    recognition.onresult = (event: SpeechRecognitionEvent) => {
      let transcript = "";
      for (let i = 0; i < event.results.length; i++) {
        transcript += event.results[i][0].transcript;
      }
      setInputValue(transcript);
    };

    recognition.onerror = () => {
      setIsListening(false);
    };

    recognition.onend = () => {
      setIsListening(false);
    };

    recognitionRef.current = recognition;
    recognition.start();
    setIsListening(true);
  }, [voiceSupported, isListening]);

  // Handle keyboard shortcuts
  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <div className="flex h-screen flex-col bg-[#F7F7F7]">
      {/* Header */}
      <div className="flex shrink-0 items-center justify-between border-b border-[#E5E5E5] bg-white px-4 py-3 md:px-6">
        <div className="flex items-center gap-3">
          <Image src="/logo.png" alt="Jaro.dev" width={32} height={32} className="size-8" />
          <div>
            <h1 className="text-sm font-semibold text-[#2E2E2E] md:text-base">
              Create your MVP plan
            </h1>
            <p className="text-xs text-[#2E2E2E]/50">
              with Jaro.dev AI - get an instant quote
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2 rounded-lg bg-[#2E2E2E] px-3 py-2 md:px-4">
          <DollarSign className="size-4 text-white" />
          <span className="text-sm font-semibold text-white md:text-base">
            {quoteTotal.total > 0
              ? `$${quoteTotal.total.toLocaleString()}`
              : "$0"}
          </span>
          <span className="hidden text-xs text-white/60 md:inline">
            est. quote
          </span>
        </div>
      </div>

      {/* Main content - split panels */}
      <div className="min-h-0 flex-1">
        {/* Desktop: resizable side-by-side */}
        <div className="hidden h-full md:block">
          <ResizablePanelGroup direction="horizontal">
            <ResizablePanel defaultSize={40} minSize={25} maxSize={60}>
              <ChatPanel
                messages={messages}
                inputValue={inputValue}
                setInputValue={setInputValue}
                isLoading={isLoading}
                isListening={isListening}
                voiceSupported={voiceSupported}
                onSend={handleSend}
                onToggleVoice={toggleVoice}
                onKeyDown={handleKeyDown}
                chatContainerRef={chatContainerRef}
                inputRef={inputRef}
              />
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={60} minSize={30}>
              <DiagramPanel
                nodes={nodes}
                edges={edges}
                onNodesChange={onNodesChange}
                onEdgesChange={onEdgesChange}
              />
            </ResizablePanel>
          </ResizablePanelGroup>
        </div>

        {/* Mobile: stacked with tabs */}
        <MobileLayout
          messages={messages}
          inputValue={inputValue}
          setInputValue={setInputValue}
          isLoading={isLoading}
          isListening={isListening}
          voiceSupported={voiceSupported}
          onSend={handleSend}
          onToggleVoice={toggleVoice}
          onKeyDown={handleKeyDown}
          chatContainerRef={chatContainerRef}
          inputRef={inputRef}
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
        />
      </div>
    </div>
  );
}

// ---------- Chat Panel ----------

interface ChatPanelProps {
  messages: ChatMessage[];
  inputValue: string;
  setInputValue: (v: string) => void;
  isLoading: boolean;
  isListening: boolean;
  voiceSupported: boolean;
  onSend: () => void;
  onToggleVoice: () => void;
  onKeyDown: (e: React.KeyboardEvent<HTMLTextAreaElement>) => void;
  chatContainerRef: React.RefObject<HTMLDivElement | null>;
  inputRef: React.RefObject<HTMLTextAreaElement | null>;
}

function ChatPanel({
  messages,
  inputValue,
  setInputValue,
  isLoading,
  isListening,
  voiceSupported,
  onSend,
  onToggleVoice,
  onKeyDown,
  chatContainerRef,
  inputRef,
}: ChatPanelProps) {
  return (
    <div className="flex h-full flex-col bg-white">
      {/* Messages */}
      <div
        ref={chatContainerRef}
        className="flex-1 space-y-4 overflow-y-auto p-4 md:p-6"
      >
        <AnimatePresence initial={false}>
          {messages.map((msg, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.2 }}
              className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
            >
              <div
                className={`max-w-[85%] rounded-xl px-4 py-3 text-sm ${
                  msg.role === "user"
                    ? "bg-[#2E2E2E] text-white"
                    : "bg-[#F7F7F7] text-[#2E2E2E]"
                }`}
              >
                {msg.role === "assistant" ? (
                  <ReactMarkdown className="prose prose-sm max-w-none [&_li]:my-0 [&_p]:my-1 [&_ul]:my-1">
                    {msg.content}
                  </ReactMarkdown>
                ) : (
                  msg.content
                )}
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {isLoading && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex justify-start"
          >
            <div className="flex items-center gap-2 rounded-xl bg-[#F7F7F7] px-4 py-3">
              <Loader2 className="size-4 animate-spin text-[#2E2E2E]/50" />
              <span className="text-sm text-[#2E2E2E]/50">Thinking...</span>
            </div>
          </motion.div>
        )}
      </div>

      {/* Input area */}
      <div className="border-t border-[#E5E5E5] p-3 md:p-4">
        <div className="flex items-end gap-2">
          {voiceSupported && (
            <button
              type="button"
              onClick={onToggleVoice}
              className={`flex size-10 shrink-0 items-center justify-center rounded-lg border transition-all ${
                isListening
                  ? "border-red-300 bg-red-50 text-red-600"
                  : "border-[#E5E5E5] bg-white text-[#2E2E2E]/50 hover:border-[#2E2E2E]/30 hover:text-[#2E2E2E]"
              }`}
            >
              {isListening ? (
                <MicOff className="size-4" />
              ) : (
                <Mic className="size-4" />
              )}
            </button>
          )}
          <div className="relative flex-1">
            <textarea
              ref={inputRef}
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={onKeyDown}
              placeholder={
                isListening ? "Listening..." : "Describe your product..."
              }
              rows={1}
              disabled={isLoading}
              className="w-full resize-none rounded-lg border border-[#E5E5E5] bg-white px-4 py-2.5 pr-12 text-sm text-[#2E2E2E] placeholder-[#2E2E2E]/30 outline-none transition-colors focus:border-[#2E2E2E]"
              style={{ minHeight: "42px", maxHeight: "120px" }}
              onInput={(e) => {
                const target = e.target as HTMLTextAreaElement;
                target.style.height = "auto";
                target.style.height = `${Math.min(target.scrollHeight, 120)}px`;
              }}
            />
            {isListening && (
              <div className="absolute right-12 top-1/2 -translate-y-1/2">
                <span className="relative flex size-2.5">
                  <span className="bg-red-400 absolute inline-flex size-full animate-ping rounded-full opacity-75" />
                  <span className="bg-red-500 relative inline-flex size-2.5 rounded-full" />
                </span>
              </div>
            )}
          </div>
          <button
            type="button"
            onClick={onSend}
            disabled={isLoading || !inputValue.trim()}
            className="flex size-10 shrink-0 items-center justify-center rounded-lg bg-[#2E2E2E] text-white transition-all hover:bg-[#1a1a1a] disabled:cursor-not-allowed disabled:opacity-40"
          >
            <Send className="size-4" />
          </button>
        </div>
      </div>
    </div>
  );
}

// ---------- Diagram Panel ----------

interface DiagramPanelProps {
  nodes: Node[];
  edges: Edge[];
  onNodesChange: ReturnType<typeof useNodesState>[2];
  onEdgesChange: ReturnType<typeof useEdgesState>[2];
}

function DiagramPanel({ nodes, edges, onNodesChange, onEdgesChange }: DiagramPanelProps) {
  return (
    <div className="h-full bg-[#FAFAFA]">
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        nodeTypes={nodeTypes}
        fitView
        fitViewOptions={{ padding: 0.3 }}
        proOptions={{ hideAttribution: true }}
        nodesDraggable={true}
        nodesConnectable={false}
        elementsSelectable={false}
        minZoom={0.3}
        maxZoom={1.5}
      >
        <Background gap={20} size={1} color="#E5E5E5" />
        <Controls showInteractive={false} />
      </ReactFlow>
    </div>
  );
}

// ---------- Mobile Layout ----------

interface MobileLayoutProps extends ChatPanelProps, Omit<DiagramPanelProps, "onNodesChange" | "onEdgesChange"> {
  onNodesChange: DiagramPanelProps["onNodesChange"];
  onEdgesChange: DiagramPanelProps["onEdgesChange"];
}

function MobileLayout(props: MobileLayoutProps) {
  const [activeTab, setActiveTab] = useState<"chat" | "diagram">("chat");

  return (
    <div className="flex h-full flex-col md:hidden">
      {/* Tab switcher */}
      <div className="flex shrink-0 border-b border-[#E5E5E5] bg-white">
        <button
          type="button"
          onClick={() => setActiveTab("chat")}
          className={`flex-1 px-4 py-2.5 text-sm font-medium transition-colors ${
            activeTab === "chat"
              ? "border-b-2 border-[#2E2E2E] text-[#2E2E2E]"
              : "text-[#2E2E2E]/50"
          }`}
        >
          Chat
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("diagram")}
          className={`flex-1 px-4 py-2.5 text-sm font-medium transition-colors ${
            activeTab === "diagram"
              ? "border-b-2 border-[#2E2E2E] text-[#2E2E2E]"
              : "text-[#2E2E2E]/50"
          }`}
        >
          Diagram
          {props.nodes.length > 0 && (
            <span className="ml-1.5 inline-flex size-5 items-center justify-center rounded-full bg-[#2E2E2E] text-[10px] text-white">
              {props.nodes.length}
            </span>
          )}
        </button>
      </div>

      {/* Content */}
      <div className="min-h-0 flex-1">
        {activeTab === "chat" ? (
          <ChatPanel
            messages={props.messages}
            inputValue={props.inputValue}
            setInputValue={props.setInputValue}
            isLoading={props.isLoading}
            isListening={props.isListening}
            voiceSupported={props.voiceSupported}
            onSend={props.onSend}
            onToggleVoice={props.onToggleVoice}
            onKeyDown={props.onKeyDown}
            chatContainerRef={props.chatContainerRef}
            inputRef={props.inputRef}
          />
        ) : (
          <DiagramPanel
            nodes={props.nodes}
            edges={props.edges}
            onNodesChange={props.onNodesChange}
            onEdgesChange={props.onEdgesChange}
          />
        )}
      </div>
    </div>
  );
}

// ---------- Wrapper with ReactFlowProvider ----------

export function MvpPlannerClient(props: MvpPlannerClientProps) {
  return (
    <ReactFlowProvider>
      <MvpPlannerInner {...props} />
    </ReactFlowProvider>
  );
}
