"use client";

import { useState, useMemo, useCallback } from "react";
import Image from "next/image";
import { useSearchParams } from "next/navigation";
import {
  CheckCircle2,
  Clock,
  Calendar,
  ArrowRight,
  Shield,
  Rocket,
  Mail,
  Loader2,
  CreditCard,
  FileCode,
  Globe,
  Cpu,
  Layers,
  Flag,
  FileText,
  ChevronDown,
  Copy,
  Check,
  Download,
} from "lucide-react";
import {
  DownloadInvoiceModal,
  type InvoiceLine,
} from "@/components/modals/download-invoice-modal";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible";
import {
  ReactFlow,
  Background,
  Controls,
  type Node,
  type Edge,
  type NodeProps,
  Handle,
  Position,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";

interface LineItem {
  code: string;
  name: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
  description?: string;
  milestoneId?: string;
}

interface Milestone {
  id: string;
  name: string;
  lineItemCodes: string[];
  amount: number;
}

interface ProductSummary {
  pages: Array<{ name: string; description: string }>;
  apis: Array<{ name: string; description: string }>;
  customLogic: Array<{ name: string; description: string }>;
}

interface DiagramNode {
  id: string;
  type: string;
  position: { x: number; y: number };
  data: {
    name: string;
    description?: string;
    isAuthenticated?: boolean;
    apiUrl?: string;
    isIncluded?: boolean;
    isAutoGenerated?: boolean;
  };
}

interface DiagramEdge {
  id: string;
  source: string;
  target: string;
}

interface DiagramData {
  nodes: DiagramNode[];
  edges: DiagramEdge[];
}

interface MVPSharedQuoteData {
  id: string;
  token: string;
  companyName: string;
  contactName: string | null;
  contactEmail: string | null;
  productSummary: unknown; // JSON from Prisma
  diagramData: unknown; // JSON from Prisma - snapshot of diagram at quote creation
  lineItems: unknown; // JSON from Prisma
  milestones: unknown; // JSON from Prisma
  subtotal: number;
  discountAmount: number;
  total: number;
  deposit: number;
  balance: number;
  expiresAt: Date;
  viewCount: number;
  createdAt: Date;
  updatedAt: Date;
  lastViewedAt: Date | null;
  depositPaidAt: Date | null;
  depositPaidAmount: number | null;
  mvpCallMapId: string;
  mvpCallMap: {
    id: string;
    name: string;
  };
}

interface MVPQuoteClientProps {
  quote: MVPSharedQuoteData;
}

// View-only node components for the diagram
function ViewOnlyPageNode({ data }: NodeProps) {
  const nodeData = data as DiagramNode["data"];
  return (
    <div
      className={`min-w-[160px] rounded-lg border-2 ${
        nodeData.isIncluded
          ? "border-primary-500 bg-primary-50"
          : nodeData.isAutoGenerated
            ? "border-primary-300 bg-primary-50/50"
            : "border-primary-400 bg-white"
      } p-3 shadow-sm`}
    >
      <Handle type="target" position={Position.Left} className="!size-3 !bg-primary-500" />
      <div className="flex items-start gap-2">
        <FileCode className="mt-0.5 size-4 shrink-0 text-primary-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {nodeData.name}
          </p>
          {nodeData.description && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {nodeData.description}
            </p>
          )}
          {nodeData.isIncluded && (
            <Badge variant="secondary" className="mt-1 text-[10px]">
              Included
            </Badge>
          )}
          {nodeData.isAutoGenerated && !nodeData.isIncluded && (
            <Badge variant="outline" className="mt-1 text-[10px]">
              Auto
            </Badge>
          )}
        </div>
      </div>
      <Handle type="source" position={Position.Right} className="!size-3 !bg-primary-500" />
    </div>
  );
}

function ViewOnlyApiNode({ data }: NodeProps) {
  const nodeData = data as DiagramNode["data"];
  return (
    <div className="min-w-[160px] rounded-lg border-2 border-success-400 bg-white p-3 shadow-sm">
      <Handle type="target" position={Position.Left} className="!size-3 !bg-success-500" />
      <div className="flex items-start gap-2">
        <Globe className="mt-0.5 size-4 shrink-0 text-success-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {nodeData.name}
          </p>
          {nodeData.apiUrl && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {nodeData.apiUrl}
            </p>
          )}
        </div>
      </div>
      <Handle type="source" position={Position.Right} className="!size-3 !bg-success-500" />
    </div>
  );
}

function ViewOnlyCustomLogicNode({ data }: NodeProps) {
  const nodeData = data as DiagramNode["data"];
  return (
    <div className="min-w-[160px] rounded-lg border-2 border-warning-400 bg-white p-3 shadow-sm">
      <Handle type="target" position={Position.Left} className="!size-3 !bg-warning-500" />
      <div className="flex items-start gap-2">
        <Cpu className="mt-0.5 size-4 shrink-0 text-warning-600" />
        <div className="min-w-0 flex-1">
          <p className="truncate text-sm font-medium text-secondary-900">
            {nodeData.name}
          </p>
          {nodeData.description && (
            <p className="mt-0.5 truncate text-xs text-secondary-500">
              {nodeData.description}
            </p>
          )}
        </div>
      </div>
      <Handle type="source" position={Position.Right} className="!size-3 !bg-warning-500" />
    </div>
  );
}

const viewOnlyNodeTypes = {
  page: ViewOnlyPageNode,
  externalApi: ViewOnlyApiNode,
  customLogic: ViewOnlyCustomLogicNode,
};

export function MVPQuoteClient({ quote }: MVPQuoteClientProps) {
  const searchParams = useSearchParams();
  const paymentStatus = searchParams?.get("payment");

  const [isProcessingPayment, setIsProcessingPayment] = useState(false);
  const [paymentError, setPaymentError] = useState<string | null>(null);
  const [email, setEmail] = useState(quote.contactEmail || "");
  const [copiedField, setCopiedField] = useState<string | null>(null);
  const [invoiceModalOpen, setInvoiceModalOpen] = useState(false);
  const [invoiceLine, setInvoiceLine] = useState<InvoiceLine | null>(null);

  const copyToClipboard = useCallback(async (text: string, fieldName: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedField(fieldName);
      setTimeout(() => setCopiedField(null), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  }, []);

  const lineItems = quote.lineItems as LineItem[];
  const milestones = quote.milestones as Milestone[];
  const productSummary = quote.productSummary as ProductSummary;
  const diagramData = quote.diagramData as DiagramData | null;
  const isAlreadyPaid = !!quote.depositPaidAt;

  // Convert diagram data to React Flow format
  const flowNodes: Node[] = useMemo(() => {
    if (!diagramData?.nodes) return [];
    return diagramData.nodes.map((node) => ({
      id: node.id,
      type: node.type,
      position: node.position,
      data: node.data,
    }));
  }, [diagramData]);

  const flowEdges: Edge[] = useMemo(() => {
    if (!diagramData?.edges) return [];
    return diagramData.edges.map((edge) => ({
      id: edge.id,
      source: edge.source,
      target: edge.target,
      animated: true,
      style: { stroke: "#94a3b8", strokeWidth: 2 },
    }));
  }, [diagramData]);

  const handlePayDeposit = async () => {
    if (!email || !email.includes("@")) {
      setPaymentError("Please enter a valid email address");
      return;
    }

    setIsProcessingPayment(true);
    setPaymentError(null);

    try {
      // TODO: Implement Stripe checkout for MVP quotes
      // For now, just show a placeholder
      setPaymentError("Payment processing coming soon. Please contact us directly.");
    } catch (error) {
      console.error("Error:", error);
      setPaymentError("An unexpected error occurred. Please try again.");
    } finally {
      setIsProcessingPayment(false);
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (date: Date) => {
    return new Date(date).toLocaleDateString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
    });
  };

  const daysUntilExpiry = useMemo(() => {
    const now = new Date();
    const expiry = new Date(quote.expiresAt);
    const diff = expiry.getTime() - now.getTime();
    return Math.ceil(diff / (1000 * 60 * 60 * 24));
  }, [quote.expiresAt]);

  // Total counts
  const totalPages = productSummary.pages.length;
  const totalApis = productSummary.apis.length;
  const totalCustomLogic = productSummary.customLogic.length;

  return (
    <div className="min-h-screen bg-secondary-50">
      {invoiceLine && (
        <DownloadInvoiceModal
          open={invoiceModalOpen}
          onClose={() => {
            setInvoiceModalOpen(false);
            setInvoiceLine(null);
          }}
          invoiceLine={invoiceLine}
        />
      )}
      {/* Header */}
      <header className="border-b border-secondary-200 bg-white">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
          <Image
            src="/logo.png"
            alt="Jaro.dev"
            width={120}
            height={40}
            className="h-8 w-auto"
          />
          <div className="flex items-center gap-2 text-sm text-secondary-500">
            <Calendar className="size-4" />
            Quote valid until {formatDate(quote.expiresAt)}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="border-b border-secondary-100 bg-white py-12">
        <div className="mx-auto max-w-5xl px-6">
          <div className="text-center">
            <Badge variant="outline" className="mb-4">
              MVP Development Proposal
            </Badge>
            <h1 className="text-4xl font-bold tracking-tight text-secondary-900">
              Your Custom Product Build
            </h1>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-secondary-600">
              A custom-built minimum viable product designed specifically for{" "}
              <span className="font-semibold text-primary-600">
                {quote.companyName}
              </span>
              . Fast to market, built to scale.
            </p>
          </div>

          {/* Urgency Banner */}
          {daysUntilExpiry <= 7 && daysUntilExpiry > 0 && (
            <div className="mx-auto mt-8 max-w-xl rounded-xl border border-warning-200 bg-warning-50 p-4 text-center">
              <div className="flex items-center justify-center gap-2 text-warning-700">
                <Clock className="size-5" />
                <span className="font-semibold">
                  This quote expires in {daysUntilExpiry} day{daysUntilExpiry !== 1 ? "s" : ""}
                </span>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Main Content */}
      <main className="mx-auto max-w-5xl px-6 py-12">
        <Tabs defaultValue="quote" className="w-full">
          <TabsList className="mb-8 grid w-full grid-cols-2">
            <TabsTrigger value="quote" className="flex items-center gap-2">
              <Rocket className="size-4" />
              Quote
            </TabsTrigger>
            <TabsTrigger value="contract" className="flex items-center gap-2">
              <FileText className="size-4" />
              Contract
            </TabsTrigger>
          </TabsList>

          <TabsContent value="quote">
            <div className="space-y-8">
              {/* Product Architecture Summary */}
              <Card className="overflow-hidden">
                <div className="border-b border-secondary-100 bg-secondary-50 px-6 py-4">
                  <h2 className="flex items-center gap-2 text-lg font-semibold text-secondary-900">
                    <Layers className="size-5 text-primary-600" />
                Product Architecture
                  </h2>
                  <p className="mt-1 text-sm text-secondary-500">
                What we are building for you
                  </p>
                </div>

                {/* Stats */}
                <div className="grid grid-cols-3 gap-4 border-b border-secondary-100 p-6">
                  <div className="rounded-lg bg-primary-50 p-4 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <FileCode className="size-5 text-primary-600" />
                      <p className="text-2xl font-bold text-primary-600">{totalPages}</p>
                    </div>
                    <p className="text-sm text-secondary-600">Pages</p>
                  </div>
                  <div className="rounded-lg bg-success-50 p-4 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <Globe className="size-5 text-success-600" />
                      <p className="text-2xl font-bold text-success-600">{totalApis}</p>
                    </div>
                    <p className="text-sm text-secondary-600">External APIs</p>
                  </div>
                  <div className="rounded-lg bg-warning-50 p-4 text-center">
                    <div className="flex items-center justify-center gap-2">
                      <Cpu className="size-5 text-warning-600" />
                      <p className="text-2xl font-bold text-warning-600">{totalCustomLogic}</p>
                    </div>
                    <p className="text-sm text-secondary-600">Custom Logic</p>
                  </div>
                </div>

                {/* Detailed breakdown */}
                <div className="divide-y divide-secondary-100">
                  {/* Pages */}
                  {productSummary.pages.length > 0 && (
                    <div className="p-6">
                      <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-secondary-500">
                        <FileCode className="size-4 text-primary-500" />
                    Application Pages
                      </h3>
                      <div className="grid gap-3 sm:grid-cols-2">
                        {productSummary.pages.map((page, idx) => (
                          <div
                            key={idx}
                            className="flex items-start gap-3 rounded-lg border border-secondary-200 p-3"
                          >
                            <div className="flex size-8 shrink-0 items-center justify-center rounded bg-primary-100">
                              <FileCode className="size-4 text-primary-600" />
                            </div>
                            <div>
                              <p className="font-medium text-secondary-900">{page.name}</p>
                              {page.description && (
                                <p className="mt-0.5 text-sm text-secondary-500">
                                  {page.description}
                                </p>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* APIs */}
                  {productSummary.apis.length > 0 && (
                    <div className="p-6">
                      <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-secondary-500">
                        <Globe className="size-4 text-success-500" />
                    External API Integrations
                      </h3>
                      <div className="grid gap-3 sm:grid-cols-2">
                        {productSummary.apis.map((api, idx) => (
                          <div
                            key={idx}
                            className="flex items-start gap-3 rounded-lg border border-secondary-200 p-3"
                          >
                            <div className="flex size-8 shrink-0 items-center justify-center rounded bg-success-100">
                              <Globe className="size-4 text-success-600" />
                            </div>
                            <div>
                              <p className="font-medium text-secondary-900">{api.name}</p>
                              {api.description && (
                                <p className="mt-0.5 text-sm text-secondary-500">
                                  {api.description}
                                </p>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* Custom Logic */}
                  {productSummary.customLogic.length > 0 && (
                    <div className="p-6">
                      <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold uppercase tracking-wider text-secondary-500">
                        <Cpu className="size-4 text-warning-500" />
                    Custom Functionality
                      </h3>
                      <div className="grid gap-3 sm:grid-cols-2">
                        {productSummary.customLogic.map((logic, idx) => (
                          <div
                            key={idx}
                            className="flex items-start gap-3 rounded-lg border border-secondary-200 p-3"
                          >
                            <div className="flex size-8 shrink-0 items-center justify-center rounded bg-warning-100">
                              <Cpu className="size-4 text-warning-600" />
                            </div>
                            <div>
                              <p className="font-medium text-secondary-900">{logic.name}</p>
                              {logic.description && (
                                <p className="mt-0.5 text-sm text-secondary-500">
                                  {logic.description}
                                </p>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              </Card>

              {/* Product Diagram - View Only */}
              {diagramData && flowNodes.length > 0 && (
                <Card className="overflow-hidden">
                  <div className="border-b border-secondary-100 bg-secondary-50 px-6 py-4">
                    <h2 className="flex items-center gap-2 text-lg font-semibold text-secondary-900">
                      <Layers className="size-5 text-primary-600" />
                  Product Architecture Diagram
                    </h2>
                    <p className="mt-1 text-sm text-secondary-500">
                  Visual overview of application structure
                    </p>
                  </div>
                  <div className="h-[400px] w-full bg-secondary-50">
                    <ReactFlow
                      nodes={flowNodes}
                      edges={flowEdges}
                      nodeTypes={viewOnlyNodeTypes}
                      fitView
                      panOnDrag
                      zoomOnScroll
                      nodesDraggable={false}
                      nodesConnectable={false}
                      elementsSelectable={false}
                      proOptions={{ hideAttribution: true }}
                    >
                      <Background color="#e2e8f0" gap={16} />
                      <Controls showInteractive={false} />
                    </ReactFlow>
                  </div>
                  <div className="border-t border-secondary-100 bg-secondary-50 px-6 py-3">
                    <div className="flex flex-wrap items-center gap-4 text-xs text-secondary-500">
                      <div className="flex items-center gap-1.5">
                        <div className="size-3 rounded border-2 border-primary-400 bg-white" />
                        <span>Page</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <div className="size-3 rounded border-2 border-success-400 bg-white" />
                        <span>External API</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <div className="size-3 rounded border-2 border-warning-400 bg-white" />
                        <span>Custom Logic</span>
                      </div>
                    </div>
                  </div>
                </Card>
              )}

              {/* Milestones */}
              {milestones.length > 0 && (
                <Card className="overflow-hidden">
                  <div className="border-b border-secondary-100 bg-secondary-50 px-6 py-4">
                    <h2 className="flex items-center gap-2 text-lg font-semibold text-secondary-900">
                      <Flag className="size-5 text-primary-600" />
                  Delivery Milestones
                    </h2>
                    <p className="mt-1 text-sm text-secondary-500">
                  Click to expand and view deliverables for each milestone.
                    </p>
                  </div>
                  <div className="divide-y divide-secondary-100">
                    {/* Deposit Milestone */}
                    <Collapsible className="group">
                      <CollapsibleTrigger className="flex w-full items-center justify-between p-4 text-left transition-colors hover:bg-secondary-50">
                        <div className="flex items-center gap-3">
                          <div className="flex size-8 items-center justify-center rounded-full bg-success-100 text-sm font-bold text-success-600">
                            {isAlreadyPaid ? (
                              <CheckCircle2 className="size-5" />
                            ) : (
                              <CreditCard className="size-4" />
                            )}
                          </div>
                          <div>
                            <h3 className="font-semibold text-secondary-900">
                              Deposit (20%)
                            </h3>
                            <p className="text-xs text-secondary-500">
                              {isAlreadyPaid ? "Paid" : "Due to begin"}
                            </p>
                          </div>
                        </div>
                        <div className="flex items-center gap-3">
                          <span
                            role="button"
                            tabIndex={0}
                            className="inline-flex h-9 shrink-0 cursor-pointer items-center justify-center gap-2 rounded-md border border-secondary-200 bg-background px-3 text-sm font-medium transition-colors hover:bg-secondary-50 hover:text-secondary-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"
                            onClick={(e) => {
                              e.preventDefault();
                              e.stopPropagation();
                              setInvoiceLine({
                                label: "MVP Deposit",
                                amount: quote.deposit,
                              });
                              setInvoiceModalOpen(true);
                            }}
                            onKeyDown={(e) => {
                              if (e.key === "Enter" || e.key === " ") {
                                e.preventDefault();
                                e.stopPropagation();
                                setInvoiceLine({
                                  label: "MVP Deposit",
                                  amount: quote.deposit,
                                });
                                setInvoiceModalOpen(true);
                              }
                            }}
                          >
                            <Download className="size-4" />
                            Download invoice
                          </span>
                          <p className="text-lg font-bold text-success-600">
                            {formatCurrency(quote.deposit)}
                          </p>
                          <ChevronDown className="size-5 text-secondary-400 transition-transform group-data-[state=open]:rotate-180" />
                        </div>
                      </CollapsibleTrigger>
                      <CollapsibleContent>
                        <div className="border-t border-secondary-100 bg-secondary-50/50 px-4 py-3">
                          <p className="text-sm text-secondary-600">
                            Initial deposit to begin development. Work starts immediately after payment is received.
                          </p>
                        </div>
                      </CollapsibleContent>
                    </Collapsible>

                    {/* Regular Milestones */}
                    {milestones.map((milestone, idx) => {
                      // Get line items for this milestone
                      const milestoneLineItems = lineItems.filter(
                        (item) => milestone.lineItemCodes.includes(item.code)
                      );
                      return (
                        <Collapsible key={milestone.id} className="group">
                          <CollapsibleTrigger className="flex w-full items-center justify-between p-4 text-left transition-colors hover:bg-secondary-50">
                            <div className="flex items-center gap-3">
                              <div className="flex size-8 items-center justify-center rounded-full bg-primary-100 text-sm font-bold text-primary-600">
                                {idx + 1}
                              </div>
                              <div>
                                <h3 className="font-semibold text-secondary-900">
                                  {milestone.name}
                                </h3>
                                <p className="text-xs text-secondary-500">
                                  {milestone.lineItemCodes.length} deliverables
                                </p>
                              </div>
                            </div>
                            <div className="flex items-center gap-3">
                              <span
                                role="button"
                                tabIndex={0}
                                className="inline-flex h-9 shrink-0 cursor-pointer items-center justify-center gap-2 rounded-md border border-secondary-200 bg-background px-3 text-sm font-medium transition-colors hover:bg-secondary-50 hover:text-secondary-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary-500 focus-visible:ring-offset-2"
                                onClick={(e) => {
                                  e.preventDefault();
                                  e.stopPropagation();
                                  setInvoiceLine({
                                    label: milestone.name,
                                    amount: milestone.amount,
                                  });
                                  setInvoiceModalOpen(true);
                                }}
                                onKeyDown={(e) => {
                                  if (e.key === "Enter" || e.key === " ") {
                                    e.preventDefault();
                                    e.stopPropagation();
                                    setInvoiceLine({
                                      label: milestone.name,
                                      amount: milestone.amount,
                                    });
                                    setInvoiceModalOpen(true);
                                  }
                                }}
                              >
                                <Download className="size-4" />
                                Download invoice
                              </span>
                              <p className="text-lg font-bold text-secondary-700">
                                {formatCurrency(milestone.amount)}
                              </p>
                              <ChevronDown className="size-5 text-secondary-400 transition-transform group-data-[state=open]:rotate-180" />
                            </div>
                          </CollapsibleTrigger>
                          <CollapsibleContent>
                            <div className="border-t border-secondary-100 bg-secondary-50/50 px-4 py-3">
                              {milestoneLineItems.length > 0 ? (
                                <div className="space-y-2">
                                  {milestoneLineItems.map((item) => (
                                    <div
                                      key={item.code}
                                      className="rounded-lg border border-secondary-100 bg-white px-3 py-2"
                                    >
                                      <p className="truncate text-sm font-medium text-secondary-900">
                                        {item.name}
                                      </p>
                                      {item.description && (
                                        <p className="truncate text-xs text-secondary-500">
                                          {item.description}
                                        </p>
                                      )}
                                    </div>
                                  ))}
                                </div>
                              ) : (
                                <p className="text-sm italic text-secondary-500">
                              No specific deliverables assigned
                                </p>
                              )}
                            </div>
                          </CollapsibleContent>
                        </Collapsible>
                      );
                    })}
                  </div>

                  {/* Total Investment */}
                  <div className="border-t border-secondary-200 bg-secondary-50 p-4">
                    <div className="space-y-2">
                      {quote.discountAmount > 0 && (
                        <>
                          <div className="flex items-center justify-between text-sm">
                            <span className="text-secondary-600">Subtotal</span>
                            <span className="font-medium text-secondary-700">{formatCurrency(quote.subtotal)}</span>
                          </div>
                          <div className="flex items-center justify-between text-sm text-success-600">
                            <span>Discount</span>
                            <span className="font-medium">-{formatCurrency(quote.discountAmount)}</span>
                          </div>
                        </>
                      )}
                      <div className="flex items-center justify-between">
                        <span className="text-lg font-semibold text-secondary-900">Total Investment</span>
                        <span className="text-xl font-bold text-primary-600">{formatCurrency(quote.total)}</span>
                      </div>
                    </div>
                  </div>
                </Card>
              )}

              {/* What is Included */}
              <Card className="p-6">
                <h2 className="mb-4 flex items-center gap-2 text-lg font-semibold text-secondary-900">
                  <Shield className="size-5 text-primary-600" />
              What is Included
                </h2>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {[
                    "Custom-built software you own",
                    "All integrations",
                    "Documentation and user guides",
                    "Source code access",
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-2">
                      <CheckCircle2 className="size-4 text-success-500" />
                      <span className="text-secondary-700">{item}</span>
                    </div>
                  ))}
                </div>
              </Card>
            </div>
          </TabsContent>

          <TabsContent value="contract">
            <Card className="overflow-hidden">
              <div className="border-b border-secondary-100 bg-secondary-50 px-6 py-4">
                <h2 className="flex items-center gap-2 text-lg font-semibold text-secondary-900">
                  <FileText className="size-5 text-primary-600" />
                  Contract for Software Development Services
                </h2>
                <p className="mt-1 text-sm text-secondary-500">
                  Please review the terms below before proceeding
                </p>
              </div>
              <div className="prose-secondary prose max-w-none p-6">
                <p className="text-secondary-600">
                  This contract is entered into on the date of deposit payment received, between
                </p>
                
                <div className="my-4 rounded-lg bg-secondary-50 p-4">
                  <p className="font-semibold text-secondary-900">Service Provider:</p>
                  <p className="text-secondary-700">Jaroslav Vorobey, CEO at Jaro.dev (Staz Limited)</p>
                </div>
                
                <p className="text-secondary-600">And</p>
                
                <div className="my-4 rounded-lg bg-secondary-50 p-4">
                  <p className="font-semibold text-secondary-900">The Client:</p>
                  <p className="text-secondary-700">The relevant client receiving Jaro.dev&apos;s official proposal.</p>
                </div>

                <div className="mt-8 space-y-6">
                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">1. Scope of Work</h3>
                    <p className="mt-2 text-secondary-700">
                      Jaro.dev agrees to develop a Minimum Viable Product (MVP) software for the Client as outlined in the official proposal and milestones documents, which contain the screens and descriptions of the features to be included in the MVP. Both parties agree that this scope of work represents the complete set of deliverables for the MVP.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">2. Payment Terms</h3>
                    <ul className="mt-2 list-disc space-y-2 pl-5 text-secondary-700">
                      <li><strong>Deposit:</strong> The Client agrees to pay Jaro.dev a 20% deposit of the total project cost prior to the commencement of any work.</li>
                      <li><strong>Milestone Payments:</strong> The remaining 80% is due upon each milestone completion, as specified in the milestones document.</li>
                      <li>Milestone payments are due within 5 working days of the milestone being completed.</li>
                      <li>Any additional features or adjustments outside of the original scope of work in the official proposal may incur additional charges, subject to mutual agreement.</li>
                    </ul>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">3. Approval of Work</h3>
                    <p className="mt-2 text-secondary-700">
                      Upon completion of each milestone, Jaro.dev will submit the deliverables for review. The MVP will be deemed complete and acceptable when it passes the following criteria:
                    </p>
                    <ul className="mt-2 list-disc space-y-2 pl-5 text-secondary-700">
                      <li>Functional testing confirms all features specified in the official proposal operate as described.</li>
                      <li>Once the milestone is approved, the client must pay Jaro.dev the amount associated with that milestone&apos;s completion.</li>
                    </ul>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">4. Confidentiality and Ownership</h3>
                    <p className="mt-2 text-secondary-700">
                      All proprietary information and project details shared between Jaro.dev and the Client are confidential. Ownership of the MVP, including all related deliverables, will belong to the client after the  milestone is approved.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">5. Termination</h3>
                    <p className="mt-2 text-secondary-700">
                      Either party may terminate this contract in writing if the other party fails to uphold the terms. In case of termination, Jaro.dev shall retain the payments made as compensation for work completed. If the client terminates the agreement during a milestone, the client must pay for the current milestone, even if not completed.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">6. Revisions and Adjustments</h3>
                    <p className="mt-2 text-secondary-700">
                      The contract includes 1 round of revisions per milestone to address feedback provided by the Client. Once a milestone has been completed and approved additional revisions will be subject to additional charges.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">7. Warranty and Support</h3>
                    <p className="mt-2 text-secondary-700">
                      Jaro.dev warrants that the MVP will perform as specified in the official proposal for a period of 90 days after final delivery. During this warranty period, Jaro.dev agrees to fix any bugs, errors, or issues at no additional cost.
                    </p>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">8. Refund Policy</h3>
                    <div className="mt-2 rounded-lg border border-success-200 bg-success-50 p-4">
                      <p className="text-secondary-700">
                        <strong>7-Day Deposit Refund:</strong> The Client may request a full refund of the deposit within the first 7 days after payment for any reason. After this 7-day period, the deposit is non-refundable.
                      </p>
                      <p className="mt-2 text-secondary-700">
                        <strong>Milestone Payments:</strong> All milestone payments are non-refundable once paid.
                      </p>
                    </div>
                  </section>

                  <section>
                    <h3 className="text-lg font-semibold text-secondary-900">9. Dispute Resolution</h3>
                    <p className="mt-2 text-secondary-700">
                      This contract shall be governed by the laws of the state of Delaware, United States. Any disputes arising from this contract shall first be resolved through mediation. If mediation fails, disputes shall be settled by binding arbitration in accordance with the rules of Delaware arbitration law.
                    </p>
                  </section>

                  <section className="mt-8 rounded-lg border-2 border-primary-200 bg-primary-50 p-6">
                    <h3 className="text-lg font-semibold text-secondary-900">Agreement</h3>
                    <p className="mt-2 text-secondary-700">
                      By sending the deposit payment, the client agrees to the terms above.
                    </p>
                    <div className="mt-4 border-t border-primary-200 pt-4">
                      <p className="font-semibold text-secondary-900">Jaro.dev Signature:</p>
                      <p className="text-secondary-700">Jaroslav Vorobey as CEO of Staz Limited (Jaro.dev)</p>
                      <p className="mt-2 text-sm text-secondary-500">1007 N. Orange St Wilmington Delaware 19801 USA</p>
                      <p className="text-sm text-secondary-500">Contact: me@jaro.dev</p>
                    </div>
                  </section>
                </div>
              </div>
            </Card>
          </TabsContent>
        </Tabs>
      </main>

      {/* Payment Section */}
      <section className="border-t border-secondary-200 bg-white py-12">
        <div className="mx-auto max-w-xl px-6">
          <Card className="overflow-hidden border-2 border-primary-500">
            <div className="bg-primary-600 px-6 py-4 text-white">
              <h3 className="font-semibold">Start Building Your MVP</h3>
              <p className="mt-1 text-sm text-primary-100">
                Send deposit via ACH/Wire to begin development
              </p>
            </div>
            <div className="p-6">
              {/* Payment Success/Cancelled Messages */}
              {paymentStatus === "success" && (
                <div className="mb-6 rounded-lg border-2 border-success-500 bg-success-50 p-4 text-center">
                  <CheckCircle2 className="mx-auto size-8 text-success-600" />
                  <p className="mt-2 font-semibold text-success-700">Payment Successful</p>
                  <p className="mt-1 text-sm text-success-600">
                    Thank you! Your deposit has been received and we will begin work immediately.
                  </p>
                </div>
              )}

              {paymentStatus === "cancelled" && (
                <div className="mb-6 rounded-lg border border-warning-300 bg-warning-50 p-4 text-center">
                  <p className="font-medium text-warning-700">Payment Cancelled</p>
                  <p className="mt-1 text-sm text-warning-600">
                    No worries! You can try again when you are ready.
                  </p>
                </div>
              )}

              {/* Already Paid */}
              {isAlreadyPaid && !paymentStatus && (
                <div className="mb-6 rounded-lg border-2 border-success-500 bg-success-50 p-4 text-center">
                  <CheckCircle2 className="mx-auto size-8 text-success-600" />
                  <p className="mt-2 font-semibold text-success-700">Deposit Paid</p>
                  <p className="mt-1 text-sm text-success-600">
                    Thank you! Your deposit of {formatCurrency(quote.depositPaidAmount || quote.deposit)} has been received.
                  </p>
                </div>
              )}

              {/* Payment Summary */}
              <div className="space-y-4">
                <div className="rounded-lg bg-success-50 p-6 text-center">
                  <p className="text-sm font-medium text-success-700">Deposit (20%)</p>
                  <p className="mt-2 text-4xl font-bold text-success-600">
                    {formatCurrency(quote.deposit)}
                  </p>
                  <p className="mt-1 text-sm text-success-600">Due to begin</p>
                </div>
              </div>

              {/* ACH Transfer Details - Only show if not paid */}
              {!isAlreadyPaid && (
                <div className="mt-6 space-y-4">
                  <div className="rounded-lg border border-secondary-200 bg-secondary-50 p-4">
                    <h4 className="font-semibold text-secondary-900">ACH / Wire Transfer Details</h4>
                    <p className="mt-1 text-xs text-secondary-500">
                      Please use the following details to send your deposit payment
                    </p>
                    
                    <div className="mt-4 space-y-3">
                      <div>
                        <p className="text-xs font-medium uppercase tracking-wide text-secondary-500">Bank Name & Address</p>
                        <div className="mt-1 flex items-start justify-between gap-2">
                          <div>
                            <p className="text-sm text-secondary-900">Community Federal Savings Bank</p>
                            <p className="text-sm text-secondary-700">89-16 Jamaica Ave, Woodhaven NY 11421, United States</p>
                          </div>
                          <button
                            onClick={() => copyToClipboard("Community Federal Savings Bank, 89-16 Jamaica Ave, Woodhaven NY 11421, United States", "bank")}
                            className="shrink-0 rounded p-1 text-secondary-400 hover:bg-secondary-200 hover:text-secondary-600"
                            title="Copy bank details"
                          >
                            {copiedField === "bank" ? <Check className="size-4 text-success-500" /> : <Copy className="size-4" />}
                          </button>
                        </div>
                      </div>
                      
                      <div className="grid grid-cols-2 gap-4">
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-secondary-500">Recipient Name</p>
                          <div className="mt-1 flex items-center justify-between gap-2">
                            <p className="text-sm font-medium text-secondary-900">Staz Limited</p>
                            <button
                              onClick={() => copyToClipboard("Staz Limited", "recipient")}
                              className="shrink-0 rounded p-1 text-secondary-400 hover:bg-secondary-200 hover:text-secondary-600"
                              title="Copy recipient name"
                            >
                              {copiedField === "recipient" ? <Check className="size-4 text-success-500" /> : <Copy className="size-4" />}
                            </button>
                          </div>
                        </div>
                        <div>
                          <p className="text-xs font-medium uppercase tracking-wide text-secondary-500">Routing Number</p>
                          <div className="mt-1 flex items-center justify-between gap-2">
                            <div>
                              <p className="font-mono text-sm font-medium text-secondary-900">026073150</p>
                              <p className="text-xs text-secondary-500">ACH & Wire</p>
                            </div>
                            <button
                              onClick={() => copyToClipboard("026073150", "routing")}
                              className="shrink-0 rounded p-1 text-secondary-400 hover:bg-secondary-200 hover:text-secondary-600"
                              title="Copy routing number"
                            >
                              {copiedField === "routing" ? <Check className="size-4 text-success-500" /> : <Copy className="size-4" />}
                            </button>
                          </div>
                        </div>
                      </div>
                      
                      <div>
                        <p className="text-xs font-medium uppercase tracking-wide text-secondary-500">Account Number</p>
                        <div className="mt-1 flex items-center justify-between gap-2">
                          <p className="font-mono text-sm font-medium text-secondary-900">822000707417</p>
                          <button
                            onClick={() => copyToClipboard("822000707417", "account")}
                            className="shrink-0 rounded p-1 text-secondary-400 hover:bg-secondary-200 hover:text-secondary-600"
                            title="Copy account number"
                          >
                            {copiedField === "account" ? <Check className="size-4 text-success-500" /> : <Copy className="size-4" />}
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <p className="text-center text-sm text-secondary-500">
                    After sending payment, please email <a href="mailto:me@jaro.dev" className="font-medium text-primary-600 hover:underline">me@jaro.dev</a> with your payment confirmation.
                  </p>
                  
                  {/* Balance Due on Delivery */}
                  <div className="rounded-lg bg-secondary-100 p-4 text-center">
                    <p className="text-sm font-medium text-secondary-700">
                      Balance Due on Delivery (80%)
                    </p>
                    <p className="mt-1 text-2xl font-bold text-secondary-900">
                      {formatCurrency(Math.round(quote.balance / milestones.length))} each
                    </p>
                    <p className="mt-1 text-sm text-secondary-500">
                      for {milestones.length} milestones
                    </p>
                  </div>
                </div>
              )}

              {/* Guarantees */}
              <ul className="mt-6 space-y-2">
                <li className="flex items-start gap-2 text-sm text-secondary-600">
                  <Rocket className="mt-0.5 size-4 shrink-0 text-primary-600" />
                  <span>Development begins immediately after deposit</span>
                </li>
                <li className="flex items-start gap-2 text-sm text-secondary-600">
                  <Shield className="mt-0.5 size-4 shrink-0 text-success-600" />
                  <span>7 day money back guarantee - full refund if unsatisfied in first 7 days</span>
                </li>
              </ul>

              {/* Contact */}
              <div className="mt-6 border-t border-secondary-200 pt-6 text-center">
                <p className="text-sm text-secondary-600">Questions about this quote?</p>
                <a
                  href={`mailto:me@jaro.dev?subject=Question about MVP quote for ${quote.companyName}`}
                  className="mt-2 inline-flex items-center gap-1 font-medium text-primary-600 hover:text-primary-700"
                >
                  <Mail className="size-4" />
                  me@jaro.dev
                </a>
              </div>
            </div>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-secondary-200 bg-white py-8">
        <div className="mx-auto max-w-5xl px-6 text-center text-sm text-secondary-500">
          <p>This quote was prepared exclusively for {quote.companyName}.</p>
          <p className="mt-1">Valid until {formatDate(quote.expiresAt)}</p>
        </div>
      </footer>
    </div>
  );
}
