import Link from "next/link";
import { Route, Sparkles } from "lucide-react";

import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { StatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { requireStaff } from "@/lib/auth-helpers";
import { listStrategies } from "@/lib/fetchers/strategies";
import { formatDate } from "@/lib/utils";

export const metadata = { title: "Strategies" };

export default async function StrategiesPage({
  searchParams,
}: {
  searchParams: Promise<{ clientId?: string }>;
}) {
  await requireStaff();
  const { clientId } = await searchParams;
  const { data: strategies, error } = await listStrategies(clientId);

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="90 day strategies"
        description="Roadmaps generated by Claude from onboarding answers and sales call transcripts."
        actions={
          <Button asChild>
            <Link href="/dashboard/strategies/new">
              <Sparkles className="mr-2 size-4" />
              Generate strategy
            </Link>
          </Button>
        }
      />

      {error && (
        <p className="rounded-md border border-danger-100 bg-danger-50 px-4 py-3 text-sm text-danger-700">
          {error}
        </p>
      )}

      {!strategies || strategies.length === 0 ? (
        <EmptyState
          icon={Route}
          title="No strategies yet"
          description="Pick a client with a completed intake form or a call transcript and Claude will draft the 30/60/90 day plan."
          action={
            <Button asChild>
              <Link href="/dashboard/strategies/new">
                <Sparkles className="mr-2 size-4" />
                Generate the first strategy
              </Link>
            </Button>
          }
        />
      ) : (
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
          {strategies.map((strategy) => {
            const actions = strategy.phases.reduce(
              (total, phase) => total + phase._count.items,
              0
            );

            return (
              <Link
                key={strategy.id}
                href={`/dashboard/strategies/${strategy.id}`}
                className="flex flex-col gap-3 rounded-lg border border-border bg-card p-5 shadow-card transition-shadow hover:shadow-card-hover"
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="line-clamp-2 text-sm font-semibold text-secondary-900">
                      {strategy.title}
                    </p>
                    <p className="truncate text-xs text-muted-foreground">
                      {strategy.client.name}
                    </p>
                  </div>
                  <StatusBadge kind="strategy" value={strategy.status} />
                </div>

                {strategy.summary && (
                  <p className="line-clamp-3 text-xs text-muted-foreground">
                    {strategy.summary}
                  </p>
                )}

                <p className="mt-auto border-t border-border pt-3 text-xs text-muted-foreground">
                  {actions} actions · {formatDate(strategy.generatedAt)}
                  {strategy.model ? ` · ${strategy.model}` : ""}
                </p>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
